spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:35296/railway
spring.datasource.username=root
spring.datasource.password=rpZOFNjpjmMruDzbUWsahXkNVCgxSSFJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}